### ISSUE TITLE
undefined method `result_count_by_group'

### ISSUE THREAD

**Issue by emilianpop** [brunoqs/pdf_export_redmine#3]
Hi, i installed on redmine 3.3.2.stable and when i want to export the issues on pdf i receive error500 and on the logfile:
Processing by IssuesController#index as PDF
  Parameters: {"export_type"=>"Full PDF", "project_id"=>"project-id"}
  Current user: user-id(id=184)
  Rendered issues/index.pdf.erb (10.0ms)
Completed 500 Internal Server Error in 130ms (ActiveRecord: 5.5ms)

ActionView::Template::Error (undefined method `**result_count_by_group**' for #<IssueQuery:0x0000000b6b69e8>):
    1: <%= raw issues_to_pdf(@issues, @project, @query) %>
  plugins/pdf_export_redmine/lib/redmine_issues_pdf_helper_patch.rb:67:in `issues_to_pdf_with_full_pdf'
  app/views/issues/index.pdf.erb:1:in `_app_views_issues_index_pdf_erb__2100545362898557189_89614600'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

do you have any idea about this error? thanks

**Comment by brunoqs** [comment]
Do you have a plugin installed that changes the redmine issues part?

**Comment by emilianpop** [comment]
hi
I have this plugins installed:

Due Date Reminder plugin
Sends notifications about due date
https://github.com/dr-prodigy/due_date_reminder

Redmine Agile plugin (Light version)
Scrum and Agile project management plugin for redmine
http://redmineup.com/pages/plugins/agile

DMSF
Document Management System Features
http://www.redmine.org/plugins/dmsf

Redmine Favourite Projects plugin
This is a plugin for Redmine to provide a list of favourite projects on My Page, Top Menu or Project Jumplist
https://github.com/syntacticvexation/redmine_favourite_projects

Thanks for reply

**Comment by brunoqs** [comment]
What version of ruby ​​are you using?

**Comment by emilianpop** [comment]
it's ruby 2.4.1 on Debian 3.2.93-1 x86_64

Thank you very much!

**Comment by brunoqs** [comment]
@emilianpop Clone branch 0.0.2 and see if it works

**Comment by emilianpop** [comment]
Hi, it works! thanks a lot!
